name: mChat
main: net.D3GN.MiracleM4n.mChat.mChat
version: 1.7.5_1
author: MiracleM4n
website: http://d3gn.net/
description: Simple..Not really... Chat modifying plugin.
commands:
    mchat:
        description: 
        usage: |
            /<command> reload
            Example: /<command> - See this info.
            Example: /<command> reload - Reload Config.
            