name: mChat
main: net.D3GN.MiracleM4n.mChat.mChat
version: 1.7.10_1
author: MiracleM4n
website: http://d3gn.net/
thread: http://forums.bukkit.org/threads/22958/
softdepend: [Spout]
commands:
    mchat:
        description: 
        usage: |
            /<command> reload [config/info]
            Example: /<command> - See this info.
            Example: /<command> reload config - Reload Config.
            Example: /<command> reload info - Reload Info.