name: mChat
main: net.D3GN.MiracleM4n.mChat.mChat
version: 1.7.9
author: MiracleM4n
website: http://d3gn.net/
thread: http://forums.bukkit.org/threads/22958/
softdepend: [Spout, mInfo]
commands:
    mchat:
        description: 
        usage: |
            /<command> reload
            Example: /<command> - See this info.
            Example: /<command> reload - Reload Config.
    mchatme:
        description: 
        usage: |
            /<command> *Message*
            Example: /<command> - See this info.
            Example: /<command> *Message* - Displays message.
        aliases: [me]
    mchatwho:
        description: 
        usage: |
            /<command> *PLAYER*
            Example: /<command> - See this info.
            Example: /<command> *PLAYER* - Displays info about player.
        aliases: [who, mwho]
    mchatafk:
        description: 
        usage: |
            /<command>
            Example: /<command> - Displays you as AFK.
        aliases: [afk, mafk]